# Generated by Django 4.0.3 on 2022-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
