# Generated by Django 4.0.3 on 2022-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypi_app', '0002_alter_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
